package com.ultrapower.cxf.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-02-03T11:18:32.702+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "UserWSImplService", 
                  wsdlLocation = "http://192.168.10.187:8080/thecxfuser/userws?wsdl",
                  targetNamespace = "http://ws.cxf.ultrapower.com/") 
public class UserWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.cxf.ultrapower.com/", "UserWSImplService");
    public final static QName UserWSImplPort = new QName("http://ws.cxf.ultrapower.com/", "UserWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.10.187:8080/thecxfuser/userws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.10.187:8080/thecxfuser/userws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserWS
     */
    @WebEndpoint(name = "UserWSImplPort")
    public UserWS getUserWSImplPort() {
        return super.getPort(UserWSImplPort, UserWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWS
     */
    @WebEndpoint(name = "UserWSImplPort")
    public UserWS getUserWSImplPort(WebServiceFeature... features) {
        return super.getPort(UserWSImplPort, UserWS.class, features);
    }

}
