package com.ultrapower.cxf.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-02-03T11:18:32.616+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.cxf.ultrapower.com/", name = "UserWS")
@XmlSeeAlso({ObjectFactory.class})
public interface UserWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "selectUserById", targetNamespace = "http://ws.cxf.ultrapower.com/", className = "com.ultrapower.cxf.ws.SelectUserById")
    @WebMethod
    @ResponseWrapper(localName = "selectUserByIdResponse", targetNamespace = "http://ws.cxf.ultrapower.com/", className = "com.ultrapower.cxf.ws.SelectUserByIdResponse")
    public com.ultrapower.cxf.ws.User selectUserById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.Integer id
    );
}
